source 'http://rubygems.org'

gem 'rails', '>= 3.0.0', '< 3.1.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2', '~> 0.2.7'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'moneta'

gem 'yajl-ruby', :require => 'yajl'
gem 'nokogiri'

# Paginator
# gem "kaminari"
# gem 'will_paginate', '3.0.pre2'

# File Uploads
# gem 'paperclip'
# gem 'carrierwave'

# gem 'devise', '~> 1.1.7'
# gem "cancan"
# gem "simple_form"
# gem 'fastercsv' # for Ruby 1.8.7+
# gem 'prawn'
# gem "haml"
# gem "haml-rails"
# gem 'validates_timeliness', '~> 3.0.5'
# gem 'acts-as-taggable-on'
gem 'acts_as_api'

# gem 'hoptoad_notifier'
# gem 'newrelic_rpm'

#gem 'SystemTimer'

group :development, :test do
  gem "rspec-rails"
  gem "capybara"
  gem 'cucumber-rails'
  gem 'factory_girl_rails'
  gem 'spork', '0.9.0.rc9'
  gem "delorean"
  gem 'rails_best_practices'
  gem 'rack-webconsole'
  gem 'ci_reporter'
end

group :test do
  gem 'simplecov', :require => false
  gem 'simplecov-rcov', :require => false
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'rb-inotify'
  gem 'libnotify'
  gem 'guard-rails'
  gem 'guard-bundler'
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'guard-spork'
end

# State machine
# gem 'aasm'
# gem 'state_machine'

# HTTP client
# gem 'typhoeus'
# gem 'rest-client', :require => 'restclient'

# Memcached client 
# gem "dalli"
# gem "memcache-client", :require => "memcache"

# Deployment tool
# gem 'capistrano'
# gem 'whiskey_disk'

# Debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Background Processing
# gem 'delayed_job'
# gem 'resque'

# Full-text search engine
# gem 'thinking-sphinx', '~> 2.0.2', :require => 'thinking_sphinx'
